[package]
name = "krxzy-zion-code/middleware"
description = "An ordered middleware pipeline for Roblox Luau applications."
version = "0.1.1"
license = "MIT"
authors = ["toxixsuff"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"

[dependencies]
